DROP PROCEDURE IF EXISTS addImage;
-- FOREIGN KEYS CONTSTRAINS DON'T ACCEPT INSERTS ON TABLES WITH REFERENCES, BUT DON'T TELL YOU SO.
DELIMITER / / CREATE PROCEDURE addImage(
  IN profilIdVar INT,
  IN urlVar VARCHAR(200),
  IN altVar VARCHAR(100)
) BEGIN DECLARE EXIT HANDLER FOR SQLEXCEPTION,
SQLWARNING BEGIN ROLLBACK;
END;
START TRANSACTION;
INSERT INTO
  gallery (profilId, url, alt)
VALUES
  (profilIdVar, urlVar, altVar);
COMMIT;
END / / DELIMITER;